spring:
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:file:~/.h2/demo;AUTO_SERVER=TRUE
    password: h2123
