spring:
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/bootdemo?serverTimezone=GMT
    password: mysql123
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    com.springboot.demo.mapper: DEBUG
