spring:
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    username: h2
    url: jdbc:h2:file:E:\myGitHub\springbootDemo\src\main\resources\h2\boot
    password: h2123
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  servlet:
    multipart:
      max-file-size: 10MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: h2
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    com.springboot.demo.mapper: DEBUG
web:
#  upload-path: /home/mwl/upload/
  upload-path: d:/articleImg/
server:
  address: 0.0.0.0