spring:
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1:3306/bootdemo?serverTimezone=GMT
    password: mysql123
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  servlet:
    multipart:
      max-file-size: 10MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    com.springboot.demo.mapper: DEBUG
web:
  upload-path: /home/mwl/upload/
server:
  address: 0.0.0.0